import poplib
import tkinter as tk


def con_server():
    try:
        account = et_account.get()
        usr_pass = et_pass.get()
        pop3_server = et.get()
        server = poplib.POP3(pop3_server)
        server.set_debuglevel(1)
        server.user(account)
        server.pass_(usr_pass)
        rsp = server.list()
        email_num = len(server.stat())
        print(server.getwelcome().decode('utf8'))
        login_info.insert('insert', '客户端:正在连接:'+pop3_server+'\n')
        login_info.insert('insert', '账号:' + account+'\n')
        server_in = server.getwelcome().decode('utf8')
        login_info.insert('insert', '服务器信息：'+str(server_in)+'\n')
        login_info.insert('insert', "服务器的响应: {1}".format(rsp)+'\n')
        login_info.insert('insert', "消息的数量: {2}".format(email_num) + '\n')
        server.close()
    except Exception as info:
        login_info.insert('insert', str(info)+'\n')
        server.close()


if __name__ == '__main__':
    root = tk.Tk()
    root.title('POP客户机程序')
    root.geometry('600x450')
    root.resizable(width=False, height=False)
    lf = tk.LabelFrame(root, text='POP Server', width=580, height=80)
    lb = tk.Label(lf, text='服务器地址')
    et = tk.Entry(lf, bd=1, width=15)
    lb1 = tk.Label(lf, text='账号')
    et_account = tk.Entry(lf, bd=1, width=15)
    lb_pass = tk.Label(lf, text='密码')
    et_pass = tk.Entry(lf, bd=1, width=15, show='*')
    lb_login = tk.Label(root, text='登录信息')
    login_info = tk.Text(root, width=82, height=20)
    btn_connect = tk.Button(root, width=20, text='连接', command=con_server)
    btn_connect.pack()
    btn_connect.place(x=10, y=412)
    login_info.pack()
    login_info.place(x=10, y=130)
    lb_login.pack()
    lb_login.place(x=15, y=100)
    et_pass.pack()
    et_pass.place(x=420, y=15)
    lb_pass.pack()
    lb_pass.place(x=380, y=15)
    et_account.pack()
    et_account.place(x=246, y=15)
    lb1.pack()
    lb1.place(x=210, y=15)
    et.pack()
    et.place(x=78, y=15)
    lb.pack()
    lb.place(x=10, y=15)
    lf.pack()
    root.mainloop()